Eluceo\EventBundle\Entity\Category:
    type: entity
    table: eluceo_event__category
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        active:
            type: boolean
        uniqueSlug:
            type: string
            length: 255
            unique: true
            gedmo:
                slug:
                    fields:
                        - name

    manyToMany:
        events:
            targetEntity: Event
            mappedBy: categories

    lifecycleCallbacks: {  }
