Eluceo\EventBundle\Entity\Event:
    type: entity
    table: eluceo_event__event
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        name2:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        shortDescription:
            type: text
            nullable: true
        active:
            type: boolean
        uniqueSlug:
            type: string
            length: 255
            unique: true
            gedmo:
                slug:
                    fields:
                        - name

    manyToMany:
        categories:
            targetEntity: Category
            inversedBy: events
            joinTable:
                name: eluceo_event_category_event
                joinColumns:
                    event_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id

    oneToMany:
        eventDates:
            targetEntity: EventDate
            mappedBy: event
            cascade:
                - all

    manyToOne:
        location:
            targetEntity: Location
            inversedBy: events
        image:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            cascade:
                - all

    lifecycleCallbacks: {  }
