eluceo.event.index:
    pattern:
        /events
    defaults:
        _controller: EluceoEventBundle:Event:index

eluceo.event.show:
    pattern:
        /events/{year}/{uniqueSlug}
    defaults:
        _controller: EluceoEventBundle:Event:show