eluceo.event.index:
    pattern:
        /
    defaults:
        _controller: EluceoEventBundle:Event:index

eluceo.event.show:
    pattern:
        /show/{uniqueSlug}
    defaults:
        _controller: EluceoEventBundle:Event:show

eluceo.event_date.show:
    pattern:
        /show/{uniqueSlug}
    defaults:
        _controller: EluceoEventBundle:Event:show

eluceo.event.export.ical:
    pattern:
        /ical
    defaults:
        _controller: EluceoEventBundle:EventExport:export
        type: ical

eluceo.event.category.index:
    pattern:
        /{categorySlug}
    defaults:
        _controller: EluceoEventBundle:Event:categoryIndex