eluceo.event.index:
    pattern:
        /
    defaults:
        _controller: EluceoEventBundle:Event:index

eluceo.event.show:
    pattern:
        /{uniqueSlug}
    defaults:
        _controller: EluceoEventBundle:Event:show

eluceo.event_date.show:
    pattern:
        /{uniqueSlug}
    defaults:
        _controller: EluceoEventBundle:Event:show

eluceo.event.category.index:
    pattern:
        /{categorySlug}
    defaults:
        _controller: EluceoEventBundle:Event:index