parameters:

services:
    eluceo.event.routing.url_generator:
        class: Eluceo\EventBundle\Routing\UrlGenerator

    eluceo.event.twig.extension.event:
        class: Eluceo\EventBundle\Twig\Extension\EventExtension
        tags:
            - { name: twig.extension }
        arguments:
            - "@eluceo.event.routing.url_generator"