parameters:
    # Admin Classes:
    eluceo.event.admin.event.class: Eluceo\EventBundle\Admin\EventAdmin
    eluceo.event.admin.event_date.class: Eluceo\EventBundle\Admin\EventDateAdmin
    eluceo.event.admin.location.class: Eluceo\EventBundle\Admin\LocationAdmin
    eluceo.event.admin.category.class: Eluceo\EventBundle\Admin\CategoryAdmin

    # Models @todo decide between ORM and ODM, etc..
    eluceo.event.model.event.class: Eluceo\EventBundle\Entity\Event
    eluceo.event.model.event_date.class: Eluceo\EventBundle\Entity\EventDate
    eluceo.event.model.location.class: Eluceo\EventBundle\Entity\Location
    eluceo.event.model.category.class: Eluceo\EventBundle\Entity\Category

services:
    eluceo.event.routing.url_generator:
        class: Eluceo\EventBundle\Routing\UrlGenerator
        arguments:
            - "@router"

    eluceo.event.twig.extension.event:
        class: Eluceo\EventBundle\Twig\Extension\EventExtension
        tags:
            - { name: twig.extension }
        arguments:
            - "@eluceo.event.routing.url_generator"

    # Blocks:
    eluceo.event.block.service.categories:
        class: Eluceo\EventBundle\Block\Service\CategoriesBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - eluceo.event.block.service.categories
            - @templating
        calls:
            - [ setCategoryManager, [ @eluceo.event.manager.category ] ]

    # Sonata Admin
    eluceo.event.admin.event:
        class: %eluceo.event.admin.event.class%
        tags:
            - { name: "sonata.admin", manager_type: orm, group: "Events", label: "Event" }
        arguments:
            - ~
            - %eluceo.event.model.event.class%
            - SonataAdminBundle:CRUD
        calls:
            - [ setLabelTranslatorStrategy, [@sonata.admin.label.strategy.underscore] ]

    eluceo.event.admin.event_date:
        class: %eluceo.event.admin.event_date.class%
        tags:
            - { name: "sonata.admin", manager_type: orm, group: "Events", label: "EventDates", show_in_dashboard: false }
        arguments:
            - ~
            - %eluceo.event.model.event_date.class%
            - SonataAdminBundle:CRUD
        calls:
            - [ setLabelTranslatorStrategy, [@sonata.admin.label.strategy.underscore] ]

    eluceo.event.admin.location:
        class: %eluceo.event.admin.location.class%
        tags:
            - { name: "sonata.admin", manager_type: orm, group: "Events", label: "Location" }
        arguments:
            - ~
            - %eluceo.event.model.location.class%
            - SonataAdminBundle:CRUD
        calls:
            - [ "addChild" , [ "@eluceo.event.admin.event" ] ]
            - [ setLabelTranslatorStrategy, [@sonata.admin.label.strategy.underscore] ]

    eluceo.event.admin.category:
        class: %eluceo.event.admin.category.class%
        tags:
            - { name: "sonata.admin", manager_type: orm, group: "Events", label: "Category" }
        arguments:
            - ~
            - %eluceo.event.model.category.class%
            - SonataAdminBundle:CRUD
        calls:
            - [ setLabelTranslatorStrategy, [@sonata.admin.label.strategy.underscore] ]